### ISSUE TITLE
🐛 Version compatibility issue: __controller_auto_register not found

### ISSUE THREAD

**Issue by krcpa** [krcpa/elif.rs#412]
## Description
After updating elif-http-derive to 0.2.1, projects using elif-http 0.8.2 encounter compilation errors because the macro expects `__controller_auto_register` which doesn't exist in that version.

## Error Message
```
error[E0433]: failed to resolve: could not find `__controller_auto_register` in `elif_http`
  --> src/modules/app/app_controller.rs:12:1
   |
12 | #[controller("/")]
   | ^^^^^^^^^^^^^^^^^^ could not find `__controller_auto_register` in `elif_http`
```

## Affected Versions
- elif-http-derive: 0.2.1
- elif-http: 0.8.2

## Expected Behavior
Version compatibility should be maintained, or version requirements should be clearly specified.

## Possible Solutions
1. Add version constraints in elif-http-derive to require compatible elif-http version
2. Provide backward compatibility in the macro
3. Release a new version of elif-http with the required `__controller_auto_register` macro

## Related Issues
- #408 (param macro fix that triggered this issue)
- #409 (body macro issue)
